object Libs {
    const val APPCOMPAT = "androidx.appcompat:appcompat"
    const val COIL = "io.coil-kt:coil"
    const val CORE_KTX = "androidx.core:core-ktx"
    const val CONSTRAINT_LAYOUT = "androidx.constraintlayout:constraintlayout"
    const val ESPRESSO_CORE = "androidx.test.espresso:espresso-core"
    const val EXT_JUNIT = "androidx.test.ext:junit"
    const val FRAGMENT_KTX = "androidx.fragment:fragment-ktx"
    const val HILT_ANDROID = "com.google.dagger:hilt-android"
    const val HILT_COMPILER = "com.google.dagger:hilt-android-compiler"
    const val JUNIT = "junit:junit"
    const val LIFECYCLE_LIVEDATA_KTX = "androidx.lifecycle:lifecycle-livedata-ktx"
    const val LIFECYCLE_VIEWMODEL_KTX = "androidx.lifecycle:lifecycle-viewmodel-ktx"
    const val MATERIAL = "com.google.android.material:material"
    const val OKHTTP_LOGGING_INTERCEPTOR = "com.squareup.okhttp3:logging-interceptor"
    const val RETROFIT = "com.squareup.retrofit2:retrofit"
    const val RETROFIT_GSON_CONVERTER = "com.squareup.retrofit2:converter-gson"
    const val TIMBER = "com.jakewharton.timber:timber"
}